apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: public
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "public"
  rules:
    - host: test-site.org
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: web-app-front
              port:
                name: front-svc
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: web-app-back
              port:
                name: back-svc



# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: ingress-service
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - host: nginx.ioo
#     - http:
#         paths:
#           - path: /
#             backend:
#               serviceName: nginx-cluster-ip-service
#               servicePort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  # namespace: ingress
spec:
  selector:
    name: nginx-ingress-microk8s
  type: LoadBalancer
  loadBalancerIP: 192.168.0.215
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

