apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-nodeport
spec:
  selector:
    app: nginx
  ports:
    - name: nginx-svc-nodeport
      protocol: TCP
      port: 9001
      nodePort: 30080
      targetPort: 80
  type: NodePort