apiVersion: v1
kind: Service
metadata:
  name: web-app-back
spec:
  selector:
    app: web-app-back
  ports:
  - name: nginx-svc
    protocol: TCP
    port: 80
    targetPort: 80
  - name: multitool-svc
    protocol: TCP
    port: 8080
    targetPort: 8080
