version: '3.5'

services:
  postgres:
    container_name: postgres12_2
    image: postgres:12
    environment:
      POSTGRES_USER: padmin
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
       - ./postgres_2:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge