---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - vector

- name: Lighthouse
  hosts: lighthouse
  become: true
  roles:
    - lighthouse
