apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minimal-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minimal-role-bind
subjects:
- kind: User
  name: arkady
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: minimal-role
  apiGroup: rbac.authorization.k8s.io
