vector_version: 0.21.1
vector_config:
  sources:
    logs:
      type: file
      read_from: beginning
      ignore_older_secs: 600
      include:
        - /home/fabryan/logs/*.log
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - logs
      endpoint: 'http://158.160.107.191:8123'
      database: sample
      table: some_logs
      skip_unknown_fields: true
      compression: gzip
      healthcheck: false
      